# Permalinks
permalink:           /:title

# Setup
title:               WTF!! GIT!!
description:             "Git is hard: screwing up is easy, & figuring out how to fix your mistakes is fucking impossible. So here are some common bad situations, & how you can get out of them in plain english."
url:                 https://git.wtf
baseurl:

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mandeep Singh
  url:               https://www.msingh.com
  email:             im@msingh.me

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/meSingh/Git.WTF
google_analytics:    UA-85622276-1
twitter:             meSingh9
github:              meSingh/Git.WTF

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
